CSL_SlotsConfig_List {
 m_SlotConfigs {
  CSL_SlotConfig "{6862BE93EB53B102}" {
   m_LoadoutPrefab "{626874113CAE4387}Prefabs/Characters/Factions/CIV/Businessman/Character_CIV_Businessman_3.et"
  }
  CSL_SlotConfig "{6862BE93EB53B109}" {
   m_LoadoutPrefab "{E024A74F8A4BC644}Prefabs/Characters/Factions/CIV/Businessman/Character_CIV_Businessman_1.et"
  }
 }
}